# Generated by Django 4.1.7 on 2023-03-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('user', 'refresh_token'), ('user', 'access_token')},
        ),
    ]
